name: AnySlab
author: jojoe77777
version: 1.3.2
description: Transform any block into a slab!
main: anyslab\main
api: [1.13.0+]
commands:
  anyslab:
    description: Transform any block into a slab!
    usage: "/anyslab create"
    permission: anyslab.create

permissions:
  anyslab.create:
    description: Allow creating slabs
    default: op
